
import { UnitTemplate } from './game-types';

export const UNIT_TEMPLATES: UnitTemplate[] = [
  {
    id: 'militia',
    name: 'Militia',
    type: 'Light Infantry',
    cost: 4,
    move: 2,
    hp: 1,
    melee: 2,
    ranged: 0,
    defense: 1,
    supply: 1,
    size: 1,
    keywords: ['Infantry'],
    ability: 'None',
    abilityDescription: 'Cheap cannon-fodder.'
  },
  {
    id: 'spearmen',
    name: 'Spearmen',
    type: 'Heavy Infantry',
    cost: 8,
    move: 2,
    hp: 2,
    melee: 4,
    ranged: 0,
    defense: 3,
    supply: 1,
    size: 1,
    keywords: ['Infantry', 'Anti-Cavalry'],
    ability: 'Anti-Cavalry Defense',
    abilityDescription: '+1 defense vs Cavalry when defending.'
  },
  {
    id: 'swordsmen',
    name: 'Swordsmen',
    type: 'Heavy Infantry',
    cost: 10,
    move: 2,
    hp: 2,
    melee: 5,
    ranged: 0,
    defense: 3,
    supply: 1,
    size: 1,
    keywords: ['Infantry'],
    ability: 'Balanced',
    abilityDescription: 'Balanced frontline fighter.'
  },
  {
    id: 'pikemen',
    name: 'Pikemen',
    type: 'Anti-Cavalry',
    cost: 9,
    move: 1,
    hp: 2,
    melee: 3,
    ranged: 0,
    defense: 4,
    supply: 1,
    size: 1,
    keywords: ['Infantry', 'Anti-Cavalry'],
    ability: 'Pike Wall',
    abilityDescription: 'Cavalry attacking suffers -2 to attack when target is Pikemen on defense.'
  },
  {
    id: 'cavalry',
    name: 'Cavalry',
    type: 'Light Horsemen',
    cost: 12,
    move: 4,
    hp: 2,
    melee: 5,
    ranged: 0,
    defense: 2,
    supply: 2,
    size: 1,
    keywords: ['Cavalry'],
    ability: 'Charge',
    abilityDescription: 'If Cavalry moves ≥2 hexes and then attacks in the same activation, get +2 to attack roll.'
  },
  {
    id: 'heavy_cavalry',
    name: 'Heavy Cavalry',
    type: 'Lancers',
    cost: 16,
    move: 3,
    hp: 3,
    melee: 7,
    ranged: 0,
    defense: 3,
    supply: 3,
    size: 1,
    keywords: ['Cavalry', 'Heavy'],
    ability: 'Heavy Charge',
    abilityDescription: 'Charge +3; additional +1 damage if attacking a flanked unit.'
  },
  {
    id: 'archers',
    name: 'Archers',
    type: 'Ranged',
    cost: 10,
    move: 2,
    hp: 1,
    melee: 1,
    ranged: 4,
    defense: 1,
    supply: 1,
    size: 1,
    keywords: ['Ranged'],
    ability: 'Volley',
    abilityDescription: 'Can shoot up to 2 hexes away. If target is adjacent, suffer -1 to attack.'
  },
  {
    id: 'skirmishers',
    name: 'Skirmishers',
    type: 'Light Ranged',
    cost: 6,
    move: 3,
    hp: 1,
    melee: 1,
    ranged: 2,
    defense: 1,
    supply: 1,
    size: 1,
    keywords: ['Ranged', 'Light'],
    ability: 'Mobile',
    abilityDescription: 'Ignore difficult terrain movement penalty.'
  },
  {
    id: 'siege_engine',
    name: 'Siege Engine',
    type: 'Artillery',
    cost: 18,
    move: 1,
    hp: 3,
    melee: 1,
    ranged: 8,
    defense: 1,
    supply: 4,
    size: 2,
    keywords: ['Siege', 'Artillery'],
    ability: 'Siege Fire',
    abilityDescription: '2-hex range, area effect: target hex and adjacent hexes affected.'
  },
  {
    id: 'engineer',
    name: 'Engineer',
    type: 'Support',
    cost: 7,
    move: 2,
    hp: 1,
    melee: 1,
    ranged: 0,
    defense: 1,
    supply: 1,
    size: 1,
    keywords: ['Support'],
    ability: 'Build',
    abilityDescription: 'Can build a Supply Camp on an empty adjacent hex by spending 2 CP.'
  },
  {
    id: 'soulcaster',
    name: 'Soulcaster',
    type: 'Support Mage',
    cost: 18,
    move: 2,
    hp: 2,
    melee: 1,
    ranged: 1,
    defense: 2,
    supply: 3,
    size: 1,
    keywords: ['Support', 'Mage'],
    ability: 'Soulcast',
    abilityDescription: '1x per skirmish - heal 1 HP to adjacent friendly unit or convert one terrain hex temporarily.'
  },
  {
    id: 'shardbearer',
    name: 'Shardbearer',
    type: 'Elite Champion',
    cost: 24,
    move: 3,
    hp: 4,
    melee: 9,
    ranged: 0,
    defense: 5,
    supply: 4,
    size: 1,
    keywords: ['Elite', 'Champion'],
    ability: 'Radiant Might',
    abilityDescription: 'Immune to morale breaks; wins ties automatically; victory margin ≥+3 pushes enemy 1 hex and deals +1 HP.'
  },
  {
    id: 'commander',
    name: 'Commander',
    type: 'General',
    cost: 20,
    move: 2,
    hp: 2,
    melee: 2,
    ranged: 0,
    defense: 3,
    supply: 2,
    size: 1,
    keywords: ['Command'],
    ability: 'Command Aura',
    abilityDescription: 'Adjacent friendly units gain +1 attack or defense (choose at start of turn). If dies, enemies within 3 hexes gain 1 morale token.'
  },
  {
    id: 'fortified_garrison',
    name: 'Fortified Garrison',
    type: 'Defensive Structure',
    cost: 30,
    move: 0,
    hp: 6,
    melee: 0,
    ranged: 0,
    defense: 6,
    supply: 5,
    size: 3,
    keywords: ['Structure', 'Fortified'],
    ability: 'Fortress',
    abilityDescription: 'Provides strong defense and prevents supply cutoffs if garrisoned. Counts as objective.'
  },
  {
    id: 'skald',
    name: 'Skald',
    type: 'Morale Support',
    cost: 6,
    move: 2,
    hp: 1,
    melee: 0,
    ranged: 0,
    defense: 1,
    supply: 1,
    size: 1,
    keywords: ['Support', 'Morale'],
    ability: 'Rally',
    abilityDescription: 'Once per two turns, remove 1 morale token from all adjacent friendly units.'
  }
];

export const getUnitTemplate = (id: string): UnitTemplate | undefined => {
  return UNIT_TEMPLATES.find(template => template.id === id);
};
